[theme]
primaryColor = "#4E79A7"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "sans serif"

[server]
headless = true

[client]
showSidebarNavigation = true